# Generated by Django 3.1.5 on 2021-01-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_productfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(related_name='cart_product', to='product.Product')),
            ],
        ),
    ]
