# Generated by Django 3.2 on 2021-04-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T',
        ),
    ]
