# Generated by Django 3.1.5 on 2021-01-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
