# Generated by Django 3.1.5 on 2021-01-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_descrption', models.TextField(blank=True, null=True)),
                ('prodcut_price', models.IntegerField(blank=True, null=True)),
                ('product_discount', models.IntegerField(blank=True, null=True)),
                ('product_discount_price', models.IntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_stock', models.BooleanField(default=True)),
                ('product_title', models.TextField(blank=True, null=True)),
                ('product_vip', models.BooleanField(default=False)),
            ],
        ),
    ]
