# Generated by Django 2.2.3 on 2021-02-25 18:15

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_descrption', models.TextField(blank=True, null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('product_discount', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True)),
                ('product_discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/java/Desktop/lesson/s/PragmatechPythonProject/ecommerce/media'), upload_to=product.models.upload_product_file_loc)),
                ('product_stock', models.BooleanField(default=False)),
                ('product_title', models.TextField(blank=True, null=True)),
                ('product_vip', models.BooleanField(default=False)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/java/Desktop/lesson/s/PragmatechPythonProject/static_cdn/product_media'), upload_to=product.models.upload_product_file_loc)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
