# Generated by Django 3.2 on 2021-04-16 20:19

import django.core.files.storage
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sevilledev/Desktop/SecondStagePragmatech/My_Ecommerce_Project/ecommerce/media'), upload_to=product.models.upload_product_file_loc),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/sevilledev/Desktop/SecondStagePragmatech/My_Ecommerce_Project/static_cdn/product_media'), upload_to=product.models.upload_product_file_loc),
        ),
    ]
