# Generated by Django 3.1.5 on 2021-01-22 18:17

import django.core.files.storage
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/abas/Desktop/lesson/static_cdn/product_media'), upload_to=product.models.upload_product_file_loc),
        ),
    ]
