# Generated by Django 3.1.5 on 2021-01-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210122_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_price',
            new_name='product_price',
        ),
    ]
