# Generated by Django 3.2.3 on 2021-08-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('analytics', '0001_initial'),
        ('billing', '0003_alter_billingprofile_user'),
        ('authtoken', '0003_tokenproxy'),
        ('cart', '0003_delete_t'),
        ('chat', '0002_room'),
        ('backend', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
