# Generated by Django 3.2.3 on 2021-08-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210811_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
